version: '3.7'
services:
  node-api:
    build:
      context: './node-api'
      args:
        - PORT=3000
    environment:
      - NODE_ENV=test
    ports:
      - '8080:3000'
  my-next-app:
    build: './my-next-app'
    ports:
      - '80:3000'
    depends_on:
      - node-api
